apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
