global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

remote_write:
  - url: "http://external-prometheus-server:9090/api/v1/write"
